### PR TITLE
Release 2018.3.0

### PR DESCRIPTION
**Pull request by RealOrangeOne**
## Changelog:
- Stop robot after 2.5 minutes when in competition mode
- Set zone and competition mode when usb with `zone-*` file is present
- Don't throw when there aren't any updates

### CODE REVIEW

**Review by trickeydan — APPROVED** [review]
This has been tested on hardware and seems to work nicely.
Thus regrettably, I am obliged to approve this to ship. Why regrettably, you ask? There is a typo at the start of the logs and this makes me sad.

**Comment by PeterJCLaw** [comment]
Did we consider _not_ shipping updates to `runusb` and `sb-vision` (where nothing has changed in a way that we _need_ to change)? If so, what were the reasons in favour of shipping those updates given the proximity to the competition?

Note: I'm not saying we shouldn't, rather I would like to check that we've fully explored the options here.

**Comment by RealOrangeOne** [comment]
I was thinking about not shipping them, but as it's been tested, i'm happy. I would rather know that `master` is what's actually shipped, rather than some arbitrary previous commit.

**Comment by PeterJCLaw** [comment]
> I was thinking about not shipping them, but as it's been tested, i'm happy.

Indeed. (Is there a spec of _what_ testing has been done?)

> I would rather know that master is what's actually shipped, rather than some arbitrary previous commit.

This is _exactly_ why git tags exist.

It's realistically impossible to know guarantee that `master` is what's on the Pis, so I don't think we should try. This is especially true when there exist other mechanisms to solve the more general issue -- knowing what is actually running on any given system is solved by versioning and tags.

**Review by Adimote — APPROVED** [review]

**Pull request merged**
