### PR TITLE
Include version information in the update archive

### PR DESCRIPTION
**Pull request by PeterJCLaw**
We store the version information in a temporary file and then cat that around to the two places we need it.

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
I would rather we add this to the update creator in `runusb`, and reuse that script here. Perhaps rebasing this branch off #15?

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I wondered about that, but the `create-update` script (somewhat intentionally) _only_ takes a list of files. It therefore has no way to know what the version information is.

**Comment by RealOrangeOne** [comment]
That's true. Could we reuse `create-update`, and inject the version file into the update file after its initial creation?

**Comment by PeterJCLaw** [comment]
Once `create-update` is available, we can do that, yes.

**Review by RealOrangeOne — APPROVED** [review]

**Pull request merged**
