### PR TITLE
Update all components to master

### PR DESCRIPTION
**Pull request by kierdavis**
I don't really know what the policy is on when (and how) we should be bumping the versions of components. This commit just brings all of them up to the latest `master` at the time of writing.

This pulls in the following changes:

* robot-api, robotd: generic arduino commands
* robot-api: cartesian coordinates
* robot-api: move serial number methods to base board class
* robot-api: fix exception thrown when camera deinits
* runusb: remove update file before updating
* runusb: no longer prints dates in the log file (because they're almost always wrong)
* robot-api, robotd, runusb, sb-vision: assorted changes regarding typing, linting, docstrings and tidying

usbmount is also updated but this does not have any functional effects (only the README is affected).

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
I think the idea is to bump components as soon as we're going to do a deploy. Although I think using this branch as a _Release Candidate_ for that deploy is useful. Nice job tracking down the major changes! I plan to write a full changelog / document the update mechanism this weekend before we ship

**Comment by kierdavis** [comment]
A "release candidate" branch sounds like a good idea.

To make that changelog I just grabbed the old and new commit IDs for each submodule from the commit diff, and then ran `git log OLD_HASH..NEW_HASH` in each submodule to get the list of new commits. This bit shouldn't be hard to script. The time-consuming part is distilling the commit log down to a list of new features and bugfixes.

**Comment by kierdavis** [comment]
Merged to pull in serial port feature from master.

**Comment by RealOrangeOne** [comment]
- Removed unnecessary logging from `robot-api` commands
- Remove `Marker.size` property
- Depricate `polar` coordinates in favour of `spherical`

Full user-facing changelog is in progress

**Comment by kierdavis** [comment]
How do we plan to stop https://github.com/sourcebots/robot-api/issues/49#issuecomment-362643552 from happening again?

**Comment by RealOrangeOne** [comment]
I don't think we can, because i'm not sure there's a real issue? It's solved entirely by custom arduino commands. Perhaps some investigation into increasing performance is worthwhile, but that's probably a longer-term goal

**Comment by kierdavis** [comment]
I was referring to the particular comment I linked to (about an attempted update not working until `dpkg -i` was manually run). I agree that the rest of the thread is unrelated to this PR.

**Comment by RealOrangeOne** [comment]
🤦‍♂️ 

It doesnt look like it's printed anything, so it's possible it never got to updating. We've made a few changes since that `runusb` version was cut, so hopefully some of those changes have fixed whatever caused this issue. I think just waiting for it to happen again is the best solution

**Pull request merged**
